/* eslint filenames/match-exported: 0 */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Logo3D(props) {
  const group = useRef();
  const { nodes } = useGLTF('/logo.gltf');

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.eye.geometry}
        material={nodes.eye.material}
        position={[-0.05, 2.5, 0]}
      />
      <mesh
        geometry={nodes.Hand.geometry}
        material={nodes.Hand.material}
        position={[0, 2.46, 0]}
      />
      <mesh
        geometry={nodes.Pupil.geometry}
        material={nodes.Pupil.material}
        position={[0.02, 2.48, 0.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.28, 1.15, 1.15]}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[-0.05, 2.5, 0]}
      />
    </group>
  );
}

useGLTF.preload('/logo.gltf');
